name = "fishyourstyle"
compatibility_date = "2025-11-22"
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20"

[observability]
enabled = true

[durable_objects]
bindings = []

[ai]
binding = "AI"

[vectorize]
binding = "VECTORIZE_INDEX"

[[placement]]
mode = "smart"

[build]
command = "npx @cloudflare/next-on-pages@1"

[unsafe.metadata]
some_metadata = "foo"

# أهم شيء:
compatibility_flags = ["nodejs_compat"]
