name = "fishyourstyle"

# تاريخ الـ compatibility (خليه زي ما هو أو أي تاريخ في الماضي)
compatibility_date = "2024-11-22"

# هنا نفعّل nodejs_compat
compatibility_flags = ["nodejs_compat"]

# هذا السطر هو اللي كان ناقص
# لازم يطابق الـ Build output directory في Cloudflare
pages_build_output_dir = ".vercel/output/static"
